version: "3.8"

services:
  chatbot-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9006:9006"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 9006 --reload
